
- name: 
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: Task 1
      ansible.tower.tower_organization:
        name: "XYZ"
        description: "Trial Task for Creating Tower Organization"
        state: present
        tower_host: localhost
        tower_oauthtoken: <deleted>
        validate_certs: false

    - name: Task 2
      ansible.tower.tower_user:
        username: "tamil"
        first_name: "tamilvanan"
        last_name: "aabhavanan"
        email: "tamilvanan7@engineer.com"
        state: present
        tower_host: localhost
        tower_oauthtoken: <deleted>
        validate_certs: false

    - name: Task 3
      ansible.tower.tower_role:
        organization: "XYZ"
        user: "tamil"
        role: admin
        state: present
        tower_host: localhost
        tower_oauthtoken: <deleted>
        validate_certs: false
