
- name: 
  hosts: webservers
  #connection: local
  become: true
  gather_facts: false

  tasks:
    - name: Task 1
      tower_organization:
        name: "XYZ"
        description: "Trial Task for Creating Tower Organization"
        state: present
        #tower_host: localhost
        tower_username: admin
        tower_password: Admin@123
        validate_certs: no
        tower_config_file: "/home/ubuntu/.tower_cli.cfg"

    - name: Task 2
      tower_user:
        username: "tamil"
        first_name: "tamilvanan"
        last_name: "aabhavanan"
        email: "tamilvanan7@engineer.com"
        state: present
        #tower_host: localhost
        tower_username: admin
        tower_password: Admin@123
        validate_certs: no
        tower_config_file: "/home/ubuntu/.tower_cli.cfg"

    - name: Task 3
      tower_role:
        organization: "XYZ"
        user: "tamil"
        role: admin
        state: present
        tower_host: localhost
        tower_username: admin
        tower_password: Admin@123
        validate_certs: no
